name: sagase
description: A Japanese-English dictionary and learning app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+20

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.29.3

isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  stacked: ^3.4.1
  stacked_services: ^1.1.1
  stacked_hooks: ^0.2.3
  flutter_hooks: any
  stacked_themes: ^0.3.13

  # Firebase
  firebase_core: 3.13.0
  firebase_analytics: 11.4.5
  firebase_crashlytics: 4.3.5

  # UI
  google_nav_bar: ^5.0.6
  settings_ui: ^2.0.2
  flip_card: # TODO change after new version published
    git:
      url: https://github.com/Moseco/flip_card
  keyboard_actions: ^4.2.0
  fl_chart: ^0.71.0
  flutter_svg: ^2.0.7
  flutter_sticky_header: ^0.7.0
  shimmer: ^3.0.0
  ruby_text: ^3.0.3
  introduction_screen: ^3.1.11
  percent_indicator: ^4.2.3
  tutorial_coach_mark: ^1.2.11
  flutter_markdown: ^0.7.3+2

  # Other
  drift: any # Version defined by sagase_dictionary
  drift_flutter: any
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.0.15
  kana_kit: ^2.1.1
  async: ^2.11.0
  archive: ^4.0.5
  google_mlkit_digital_ink_recognition: ^0.14.1
  google_mlkit_text_recognition: ^0.15.0
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  mecab_dart:
    git:
      url: https://github.com/Moseco/mecab_dart
      ref: '338acd9'
  path: ^1.8.3
  flutter_file_dialog: ^3.0.1
  sagase_dictionary:
    git:
      url: https://github.com/Moseco/sagase_dictionary
      ref: '4ea66ef'
  url_launcher: ^6.1.12
  dio: ^5.3.3
  in_app_review: ^2.0.8
  disk_space_plus: ^0.2.5
  share_plus: ^10.1.4
  app_links: ^6.3.2
  uri_to_file:
    git:
      url: https://github.com/chan150/uri-to-file
      ref: 'ddb5dff'
  security_scoped_resource: ^0.0.2
  sanitize_filename: ^1.0.5
  image_picker: ^1.1.2
  flutter_exif_rotation:
    git:
      url: https://github.com/Moseco/flutter_exif_rotation
      ref: '55b72de'

dependency_overrides:
  flutter_statusbarcolor_ns:
    git:
      url: https://github.com/uintdev/flutter_statusbarcolor/
      ref: 'd870cb2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: any
  stacked_generator: ^1.4.0
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  mockito: ^5.4.2
  plugin_platform_interface: ^2.1.4
  path_provider_platform_interface: ^2.0.6

flutter:
  fonts:   
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
    # Custom font that merges sans latin characters with serif japanese characters
    - family: NotoSansWithSerifJP
      fonts:
        - asset: assets/fonts/Noto_Sans_With_Serif_JP/NotoSansWithSerifJP-Regular.ttf
        - asset: assets/fonts/Noto_Sans_With_Serif_JP/NotoSansWithSerifJP-Bold.ttf

  uses-material-design: true

  assets:
    # Dictionary and mecab files for debug
    # - assets/dictionary/dictionary.zip
    # - assets/mecab/mecab.zip
    # - assets/dictionary/proper_noun_dictionary.zip
    # Radical positions images
    - assets/images/radical_positions/
    # App Icon
    - assets/images/icon.png
    