name: sagase
description: A Japanese-English dictionary and learning tool.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  stacked: ^2.3.15
  stacked_services: ^0.9.9
  stacked_hooks: ^0.2.2
  flutter_hooks: ^0.18.5+1
  stacked_themes: ^0.3.9

  # UI
  google_nav_bar: ^5.0.6
  settings_ui: ^2.0.2
  flip_card: ^0.7.0
  keyboard_actions: ^4.1.0
  fl_chart: ^0.55.2
  flutter_svg: ^1.1.6
  flutter_sticky_header: ^0.6.5
  shimmer: ^2.0.0
  ruby_text: ^3.0.1

  # Other
  isar: ^3.1.0+1
  isar_flutter_libs: any
  xml: ^6.1.0
  path_provider: ^2.0.11
  kana_kit: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/kana_kit
  async: ^2.8.2
  archive: ^3.3.1
  google_mlkit_digital_ink_recognition: ^0.6.0
  intl: ^0.18.0
  shared_preferences: ^2.0.17
  mecab_dart: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/mecab_dart
  path: ^1.8.1
  flutter_file_dialog: ^3.0.0
  sagase_dictionary:
    git:
      url: https://github.com/Moseco/sagase_dictionary
      ref: 0a880fa

# Dependency override to make mecab_dart compatible with flutter_test
dependency_overrides:
  path: 1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: any
  stacked_generator: ^0.7.15
  isar_generator: any
  mockito: ^5.3.2
  plugin_platform_interface: ^2.1.4
  path_provider_platform_interface: ^2.0.6

flutter:
  fonts:   
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf

  uses-material-design: true

  assets:
    - assets/dictionary_source/db_export.zip
    # Kanji radical positions images
    - assets/images/kanji_radical_positions/
    # Files for mecab
    - assets/mecab/ipadic.zip
    