name: sagase
description: A Japanese-English dictionary and learning tool.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  stacked: ^2.3.15
  stacked_services: ^0.9.4
  stacked_hooks: ^0.2.2
  flutter_hooks: ^0.18.5+1

  # UI
  google_nav_bar: ^5.0.6
  settings_ui: ^2.0.2

  # Other
  isar: ^3.0.0
  isar_flutter_libs: any
  xml: ^6.1.0
  path_provider: ^2.0.11
  kana_kit: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/kana_kit
  async: ^2.8.2
  archive: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: any
  stacked_generator: ^0.7.15
  isar_generator: any
  path: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/dictionary_source/JMdict_e_examp # Should be removed for release builds
    - assets/dictionary_source/kanjidic2.xml # Should be removed for release builds
    - assets/dictionary_source/db_export.zip
    