name: sagase
description: A Japanese-English dictionary and learning tool.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.11.0+8

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  stacked: ^3.4.1
  stacked_services: ^1.1.1
  stacked_hooks: ^0.2.3
  flutter_hooks: any
  stacked_themes: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/themes

  # Firebase
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4

  # UI
  google_nav_bar: ^5.0.6
  settings_ui: ^2.0.2
  flip_card: ^0.7.0
  keyboard_actions: ^4.2.0
  fl_chart: ^0.64.0
  flutter_svg: ^2.0.7
  flutter_sticky_header: ^0.6.5
  shimmer: ^3.0.0
  ruby_text: ^3.0.3
  introduction_screen: ^3.1.11
  percent_indicator: ^4.2.3

  # Other
  isar: ^3.1.0+1
  isar_flutter_libs: any
  path_provider: ^2.0.15
  kana_kit: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/kana_kit
  async: ^2.11.0
  archive: ^3.4.9
  google_mlkit_digital_ink_recognition: ^0.10.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  mecab_dart: ^0.1.6
  path: ^1.8.3
  flutter_file_dialog: ^3.0.1
  sagase_dictionary:
    git:
      url: https://github.com/Moseco/sagase_dictionary
      ref: '015d835'
  url_launcher: ^6.1.12
  dio: ^5.3.3
  in_app_review: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: any
  stacked_generator: ^1.4.0
  isar_generator: any
  mockito: ^5.4.2
  plugin_platform_interface: ^2.1.4
  path_provider_platform_interface: ^2.0.6

flutter:
  fonts:   
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
    # Custom font that merges sans latin characters with serif japanese characters
    - family: NotoSansWithSerifJP
      fonts:
        - asset: assets/fonts/Noto_Sans_With_Serif_JP/NotoSansWithSerifJP-Regular.ttf
        - asset: assets/fonts/Noto_Sans_With_Serif_JP/NotoSansWithSerifJP-Bold.ttf

  uses-material-design: true

  assets:
    # Dictionary and mecab files for debug
    # - assets/dictionary/base_dictionary.zip
    # - assets/mecab/mecab_dictionary.zip
    # Kanji radical positions images
    - assets/images/kanji_radical_positions/
    # App Icon
    - assets/images/icon.png
    