// Components used by the kanji component search, grouped by stroke count.
//
// Pass one argument when the displayed glyph is also what gets stored in
// `Kanji.components` and queried in the DB. Pass a second argument when the
// glyph in the picker is a radical/variant form whose searchable counterpart
// is a different kanji — e.g. `KanjiComponent('⺅', '化')`.
class KanjiComponent {
  final String display;
  final String search;

  const KanjiComponent(String c, [String? search])
      : display = c,
        search = search ?? c;
}

const kanjiComponentGroups = <(int, List<KanjiComponent>)>[
  (1, [
    KanjiComponent('一'),
    KanjiComponent('｜'),
    KanjiComponent('丶'),
    KanjiComponent('ノ'),
    KanjiComponent('乙'),
    KanjiComponent('亅'),
  ]),
  (2, [
    KanjiComponent('二'),
    KanjiComponent('亠'),
    KanjiComponent('人'),
    KanjiComponent('⺅', '化'),
    KanjiComponent('𠆢', '个'),
    KanjiComponent('儿'),
    KanjiComponent('入'),
    KanjiComponent('ハ'),
    KanjiComponent('丷', '并'),
    KanjiComponent('冂'),
    KanjiComponent('冖'),
    KanjiComponent('冫'),
    KanjiComponent('几'),
    KanjiComponent('凵'),
    KanjiComponent('刀'),
    KanjiComponent('⺉', '刈'),
    KanjiComponent('力'),
    KanjiComponent('勹'),
    KanjiComponent('匕'),
    KanjiComponent('匚'),
    KanjiComponent('十'),
    KanjiComponent('卜'),
    KanjiComponent('卩'),
    KanjiComponent('厂'),
    KanjiComponent('厶'),
    KanjiComponent('又'),
    KanjiComponent('マ'),
    KanjiComponent('九'),
    KanjiComponent('ユ'),
    KanjiComponent('乃'),
    KanjiComponent('𠂉', '乞'),
  ]),
  (3, [
    KanjiComponent('⻌', '込'),
    KanjiComponent('口'),
    KanjiComponent('囗'),
    KanjiComponent('土'),
    KanjiComponent('士'),
    KanjiComponent('夂'),
    KanjiComponent('夕'),
    KanjiComponent('大'),
    KanjiComponent('女'),
    KanjiComponent('子'),
    KanjiComponent('宀'),
    KanjiComponent('寸'),
    KanjiComponent('小'),
    KanjiComponent('⺌', '尚'),
    KanjiComponent('尢'),
    KanjiComponent('尸'),
    KanjiComponent('屮'),
    KanjiComponent('山'),
    KanjiComponent('川'),
    KanjiComponent('巛'),
    KanjiComponent('工'),
    KanjiComponent('已'),
    KanjiComponent('巾'),
    KanjiComponent('干'),
    KanjiComponent('幺'),
    KanjiComponent('广'),
    KanjiComponent('廴'),
    KanjiComponent('廾'),
    KanjiComponent('弋'),
    KanjiComponent('弓'),
    KanjiComponent('ヨ'),
    KanjiComponent('彑'),
    KanjiComponent('彡'),
    KanjiComponent('彳'),
    KanjiComponent('⺖', '忙'),
    KanjiComponent('⺘', '扎'),
    KanjiComponent('⺡', '汁'),
    KanjiComponent('⺨', '犯'),
    KanjiComponent('⺾', '艾'),
    KanjiComponent('⻏', '邦'),
    KanjiComponent('⻖', '阡'),
    KanjiComponent('也'),
    KanjiComponent('亡'),
    KanjiComponent('及'),
    KanjiComponent('久'),
  ]),
  (4, [
    KanjiComponent('⺹', '老'),
    KanjiComponent('心'),
    KanjiComponent('戈'),
    KanjiComponent('戸'),
    KanjiComponent('手'),
    KanjiComponent('支'),
    KanjiComponent('攵'),
    KanjiComponent('文'),
    KanjiComponent('斗'),
    KanjiComponent('斤'),
    KanjiComponent('方'),
    KanjiComponent('无'),
    KanjiComponent('日'),
    KanjiComponent('曰'),
    KanjiComponent('月'),
    KanjiComponent('木'),
    KanjiComponent('欠'),
    KanjiComponent('止'),
    KanjiComponent('歹'),
    KanjiComponent('殳'),
    KanjiComponent('比'),
    KanjiComponent('毛'),
    KanjiComponent('氏'),
    KanjiComponent('气'),
    KanjiComponent('水'),
    KanjiComponent('火'),
    KanjiComponent('⺣', '杰'),
    KanjiComponent('爪'),
    KanjiComponent('父'),
    KanjiComponent('爻'),
    KanjiComponent('爿'),
    KanjiComponent('片'),
    KanjiComponent('牛'),
    KanjiComponent('犬'),
    KanjiComponent('⺭', '礼'),
    KanjiComponent('王'),
    KanjiComponent('元'),
    KanjiComponent('井'),
    KanjiComponent('勿'),
    KanjiComponent('尤'),
    KanjiComponent('五'),
    KanjiComponent('屯'),
    KanjiComponent('毋'),
    KanjiComponent('巴'),
  ]),
  (5, [
    KanjiComponent('玄'),
    KanjiComponent('瓦'),
    KanjiComponent('甘'),
    KanjiComponent('生'),
    KanjiComponent('用'),
    KanjiComponent('田'),
    KanjiComponent('疋'),
    KanjiComponent('疒', '疔'),
    KanjiComponent('癶'),
    KanjiComponent('白'),
    KanjiComponent('皮'),
    KanjiComponent('皿'),
    KanjiComponent('目'),
    KanjiComponent('矛'),
    KanjiComponent('矢'),
    KanjiComponent('石'),
    KanjiComponent('示'),
    KanjiComponent('禸', '禹'),
    KanjiComponent('禾'),
    KanjiComponent('穴'),
    KanjiComponent('立'),
    KanjiComponent('⻂', '初'),
    KanjiComponent('世'),
    KanjiComponent('巨'),
    KanjiComponent('冊'),
    KanjiComponent('母'),
    KanjiComponent('⺲', '買'),
    KanjiComponent('牙'),
  ]),
  (6, [
    KanjiComponent('瓜'),
    KanjiComponent('竹'),
    KanjiComponent('米'),
    KanjiComponent('糸'),
    KanjiComponent('缶'),
    KanjiComponent('羊'),
    KanjiComponent('羽'),
    KanjiComponent('而'),
    KanjiComponent('耒'),
    KanjiComponent('耳'),
    KanjiComponent('聿'),
    KanjiComponent('肉'),
    KanjiComponent('自'),
    KanjiComponent('至'),
    KanjiComponent('臼'),
    KanjiComponent('舌'),
    KanjiComponent('舟'),
    KanjiComponent('艮'),
    KanjiComponent('色'),
    KanjiComponent('虍'),
    KanjiComponent('虫'),
    KanjiComponent('血'),
    KanjiComponent('行'),
    KanjiComponent('衣'),
    KanjiComponent('西'),
  ]),
  (7, [
    KanjiComponent('臣'),
    KanjiComponent('見'),
    KanjiComponent('角'),
    KanjiComponent('言'),
    KanjiComponent('谷'),
    KanjiComponent('豆'),
    KanjiComponent('豕'),
    KanjiComponent('豸'),
    KanjiComponent('貝'),
    KanjiComponent('赤'),
    KanjiComponent('走'),
    KanjiComponent('足'),
    KanjiComponent('身'),
    KanjiComponent('車'),
    KanjiComponent('辛'),
    KanjiComponent('辰'),
    KanjiComponent('酉'),
    KanjiComponent('釆'),
    KanjiComponent('里'),
    KanjiComponent('舛'),
    KanjiComponent('麦'),
  ]),
  (8, [
    KanjiComponent('金'),
    KanjiComponent('長'),
    KanjiComponent('門'),
    KanjiComponent('隶'),
    KanjiComponent('隹'),
    KanjiComponent('雨'),
    KanjiComponent('青'),
    KanjiComponent('非'),
    KanjiComponent('奄'),
    KanjiComponent('岡'),
    KanjiComponent('免'),
    KanjiComponent('斉'),
  ]),
  (9, [
    KanjiComponent('面'),
    KanjiComponent('革'),
    KanjiComponent('韭'),
    KanjiComponent('音'),
    KanjiComponent('頁'),
    KanjiComponent('風'),
    KanjiComponent('飛'),
    KanjiComponent('食'),
    KanjiComponent('首'),
    KanjiComponent('香'),
    KanjiComponent('品'),
  ]),
  (10, [
    KanjiComponent('馬'),
    KanjiComponent('骨'),
    KanjiComponent('高'),
    KanjiComponent('髟'),
    KanjiComponent('鬥'),
    KanjiComponent('鬯'),
    KanjiComponent('鬲'),
    KanjiComponent('鬼'),
    KanjiComponent('竜'),
    KanjiComponent('韋'),
  ]),
  (11, [
    KanjiComponent('魚'),
    KanjiComponent('鳥'),
    KanjiComponent('鹵'),
    KanjiComponent('鹿'),
    KanjiComponent('麻'),
    KanjiComponent('亀'),
    KanjiComponent('啇', '滴'),
    KanjiComponent('黄'),
    KanjiComponent('黒'),
  ]),
  (12, [
    KanjiComponent('黍'),
    KanjiComponent('黹'),
    KanjiComponent('無'),
    KanjiComponent('歯'),
  ]),
  (13, [
    KanjiComponent('黽'),
    KanjiComponent('鼎'),
    KanjiComponent('鼓'),
    KanjiComponent('鼠'),
  ]),
  (14, [
    KanjiComponent('鼻'),
    KanjiComponent('齊'),
  ]),
  (17, [KanjiComponent('龠')]),
];

final Set<String> allKanjiComponentSearchChars = {
  for (final group in kanjiComponentGroups)
    for (final component in group.$2) component.search,
};
